skill_trainer : LVD.runner.BaseTrainer       # pretrain trainer 
rl_trainer : LVD.rl.Flat_RL_Trainer          # few-shot adaptation trainer 
buffer_cls : LVD.collector.GC_Buffer_Relabel # buffer class

with_gcsl: true # deprecated.
   
tanh : true # action space : tanh normal
gc : true   # deprecated

consistency_update : true  # deprecated
model_update : false       # deprecated

policy : 
  n_blocks : 5
  hidden_dim : 128
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

# not used. 
q_function : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 1
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0