skill_trainer : LVD.runner.BaseTrainer
rl_trainer : LVD.rl.Flat_RL_Trainer
buffer_cls : LVD.collector.GC_Buffer_Relabel

with_gcsl: true

consistency_update : true
model_update : false
binary_reward : true
tanh : true

policy : 
  n_blocks : 5
  hidden_dim : 128
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

q_function : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 1
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0