subseq_len : 11
tanh : true
skill_trainer : LVD.runner.Diversity_Trainer
rl_trainer : LVD.rl.rl_trainer.RL_Trainer
consistency_update : true

invD_lr : 1e-6
D_lr : 1e-5
f_lr : 1e-8


state_encoder :
  n_blocks : 5
  hidden_dim : 128 
  module_type : linear
  linear_cls : LVD.modules.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0

state_decoder :
  n_blocks : 5
  hidden_dim : 128 
  module_type : linear
  linear_cls : LVD.modules.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0

dynamics :
  n_blocks : 5
  hidden_dim : 128 
  module_type : linear
  linear_cls : LVD.modules.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0

inverse_dynamics :
  n_blocks : 5
  hidden_dim : 128
  module_type : linear
  linear_cls : LVD.modules.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0

subgoal_generator :
  n_blocks  :  5
  hidden_dim  : 128
  module_type : linear
  linear_cls  : LVD.modules.LinearBlock
  norm_cls  : torch.nn.LayerNorm
  act_cls  : torch.nn.Mish
  tanh  : False
  bias  : true
  dropout : 0   

prior : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 20
  module_type : linear
  linear_cls : LVD.modules.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

ppc : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 20
  module_type : linear
  linear_cls : LVD.modules.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

skill_encoder : 
  n_blocks : 1
  hidden_dim : 128
  out_dim : 20
  module_type : rnn
  rnn_cls : torch.nn.LSTM
  linear_cls : LVD.modules.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0
  batch_first : true
  
skill_decoder : 
  n_blocks : 5
  hidden_dim : 128
  module_type : linear
  linear_cls : LVD.modules.LinearBlock
  norm_cls : torch.nn.BatchNorm1d
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

q_function : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 1
  module_type : linear
  linear_cls : LVD.modules.LinearBlock
  norm_cls :  torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0