subseq_len : 11
tanh : true

state_encoder :
    n_blocks : 5
    # in_feature : self.state_dim, # state_dim + latent_dim 
    hidden_dim : 128 
    # hidden_dim = self.hidden_dim, 
    # out_dim = self.latent_state_dim, # when variational inference
    linear_cls : LVD.modules.base.LinearBlock
    norm_cls : torch.nn.LayerNorm
    act_cls : torch.nn.Mish
    bias : true
    dropout : 0

state_decoder :
    n_blocks : 5
    # in_feature : self.state_dim, # state_dim + latent_dim 
    hidden_dim : 128 
    # hidden_dim = self.hidden_dim, 
    # out_dim = self.latent_state_dim, # when variational inference
    linear_cls : LVD.modules.base.LinearBlock
    norm_cls : torch.nn.LayerNorm
    act_cls : torch.nn.Mish
    bias : true
    dropout : 0

dynamics :
    n_blocks : 5
    # in_feature : self.state_dim, # state_dim + latent_dim 
    hidden_dim : 128 
    # hidden_dim = self.hidden_dim, 
    # out_dim = self.latent_state_dim, # when variational inference
    linear_cls : LVD.modules.base.LinearBlock
    norm_cls : torch.nn.LayerNorm
    act_cls : torch.nn.Mish
    bias : true
    dropout : 0

inverse_dynamics :
    n_blocks : self.n_Layers
    hidden_dim : 128
    out_dim : 20
    norm_cls : torch.nn.LayerNorm
    act_cls : torch.nn.Mish
    linear_cls : LVD.modules.base.LinearBlock
    bias : true
    dropout : 0

subgoal_generator :
    n_blocks  :  5
    # in_feature = self.latent_state_dim + self.n_goal, # state_dim + latent_dim 
    hidden_dim  : 128
    # out_dim  : self.latent_state_dim
    norm_cls  : torch.nn.LayerNorm
    act_cls  : torch.nn.Mish
    linear_cls  : LVD.modules.base.LinearBlock
    tanh  : False
    bias  : true
    dropout : 0   

prior : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 20
  module_type : "linear"
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

skill_encoder : 
  n_blocks : 1
  hidden_dim : 128
  out_dim : 20
  module_type : "rnn"
  rnn_cls : torch.nn.LSTM
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0
  batch_first : true
  
skill_decoder : 
  n_blocks : 5
  hidden_dim : 128
  module_type : "linear"
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.BatchNorm1d
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

high_policy : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 20
  module_type : "linear"
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.BatchNorm1d
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0