skill_trainer : LVD.runner.BaseTrainer
rl_trainer : LVD.rl.Flat_RL_Trainer
with_gcsl: true

consistency_update : true
model_update : false


policy : 
  n_blocks : 5
  hidden_dim : 128
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0


high_level_policy : 
  n_blocks : 5
  hidden_dim : 128
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : false
  bias : true
  dropout : 0


q_function : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 1
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0