subseq_len : 11
tanh : false

prior : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 20
  module_type : "linear"
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : false
  bias : true
  dropout : 0

skill_encoder : 
  n_blocks : 1
  hidden_dim : 128
  out_dim : 20
  module_type : "rnn"
  rnn_cls : torch.nn.LSTM
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : false
  bias : true
  dropout : 0
  batch_first : true
  
skill_decoder : 
  n_blocks : 5
  hidden_dim : 128
  module_type : "linear"
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.BatchNorm1d
  act_cls : torch.nn.Mish
  tanh : false
  bias : true
  dropout : 0

high_policy : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 20
  module_type : "linear"
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.BatchNorm1d
  act_cls : torch.nn.Mish
  tanh : false
  bias : true
  dropout : 0