subseq_len : 11
tanh : true

skill_trainer : LVD.runner.BaseTrainer
consistency_update : false

state_encoder :
  n_blocks : 5
  hidden_dim : 128 
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0


state_decoder :
  n_blocks : 5
  hidden_dim : 128 
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0

dynamics :
  n_blocks : 5
  hidden_dim : 128 
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0

reward_function :
  n_blocks : 5
  hidden_dim : 128 
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0


prior : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 20
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

skill_encoder : 
  n_blocks : 1
  hidden_dim : 128
  out_dim : 20
  module_type : rnn
  rnn_cls : torch.nn.LSTM
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0
  batch_first : true
  
skill_decoder : 
  n_blocks : 5
  hidden_dim : 128
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.BatchNorm1d
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

high_policy : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 20
  module_type : linear
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : torch.nn.LayerNorm
  act_cls : torch.nn.Mish
  tanh : true
  bias : true
  dropout : 0

q_function : 
  n_blocks : 5
  hidden_dim : 128
  out_dim : 1
  linear_cls : LVD.modules.base.LinearBlock
  norm_cls : None
  act_cls : torch.nn.Mish
  bias : true
  dropout : 0