# from ..base_config import BaseDataConfig
# from easydict import EasyDict as edict
# # from ...data.carla.carla_data_loader import *
# from ...data import *


# MODE_DICT = {
#     "sc" : CARLA_Dataset,
#     "sc_dreamer" : CARLA_Dataset,
#     "simpl" : CARLA_Dataset,
#     "skimo" : CARLA_Dataset,
#     "gc_skimo" : CARLA_Dataset,
#     "gc_div_joint" : CARLA_Dataset_Diversity,
# }

env_name : "carla"
robotics : true

state_dim : 17
n_obj : 17
n_env : 0
n_goal : 2
action_dim : 2
normalize : true

subseq_len : 11
max_seq_len : 3000
data_dir : "."
epoch_cycles_train : 50


batch_size : 1024
mixin_start : 30
mixin_ratio : 0.05
plan_H : 100
epochs : 70
warmup_steps : 30

latent_dim : 10
latent_state_dim : 32
reg_beta : 1e-5
wae_coef : 1
val_data_size : 5000

time_limit : 3000
target_kl_start : 2
target_kl_end : 2
init_alpha : 0.0005
only_increase : true
auto_alpha : false
reuse_rate : 512
q_warmup : 5000
q_weight : 1
precollect : 20
early_stop_threshold : 0.8
max_reward : 4
use_hidden : true
consistency_lr : 1e-8
policy_lr : 3e-6