env_name : kitchen
env_name_offline : kitchen-mixed-v0
robotics : true

# env_cls : LVD.envs.KitchenEnv_GC
# env_cfg : LVD.envs.kitchen_cfg
# task_cls : LVD.envs.KitchenTask_GC
# meta_tasks : LVD.envs.kitchen_meta_tasks
# target_tasks : LVD.envs.kitchen_tasks
# ablation_tasks : LVD.envs.kitchen_ablation_tasks


envtask_cfg : LVD.envs.Kitchen_EnvTaskConfig


state_dim : 30
n_obj : 9
n_env : 21
n_goal : 30
action_dim : 9
normalize : false

subseq_len : 11
max_seq_len : 280
epoch_cycles_train : 50


batch_size : 500
mixin_start : 1
mixin_ratio : 0.05
plan_H : 100
epochs : 70
# epochs : 40
warmup_steps : 20

skill_dim : 10
latent_state_dim : 32
reg_beta : 0.0005
prior_state_dim : 30
wae_coef : 10
val_data_size : 5000

time_limit : 280
target_kl_start : 50
target_kl_end : 15
init_alpha : 0.005
increasing_alpha : false
auto_alpha : false
reuse_rate : 512
q_warmup : 10_000
q_weight : 1
precollect : 20
early_stop_threshold : ${multiply:4, 0.8}
max_reward : 4
use_hidden : true
consistency_lr : 1e-8
policy_lr : 3e-5
buffer_size : 3000
n_episode : 300
kl_decay : 0.99