env_name : kitchen
env_name_offline : kitchen-mixed-v0
manipulation : true

envtask_cfg : LVD.envs.Kitchen_EnvTaskConfig
binary_reward : false
std_factor : 1.35
norm_G : true
discount : false
normalize_state : false

# flat_Dtest 
testtest : false

# Skimo


# WGCSL / RIS
reward_threshold : 3



state_dim : 30
n_pos : 9
n_nonPos : 0
n_env : 21
n_goal : 30
action_dim : 9

subseq_len : 11
max_seq_len : 280
epoch_cycles_train : 100
offline_buffer_size : 10000

batch_size : 1024
mixin_start : 1
mixin_ratio : 0.1
plan_H : 160
epochs : 70
# epochs : 40
warmup_steps : 10

skill_dim : 10
latent_state_dim : 256
reg_beta : 0.0005
state_reg_beta : 1e-4
prior_state_dim : 30
wae_coef : 10
val_data_size : 5000

time_limit : 280
target_kl_start : 50
target_kl_end : 15
init_alpha : 0.005
increasing_alpha : false
auto_alpha : false
reuse_rate : 4000
step_per_ep : 100
q_warmup : 10_000
q_weight : 1
precollect : 20
early_stop_threshold : ${multiply:4, 0.8}
max_reward : 4
use_hidden : true
consistency_lr : 3e-5

# min_lr * 0.05
policy_lr : 5e-7
# policy_lr : 3e-5
buffer_size : 20000
n_episode : 150
kl_decay : 0.99


# invD_lr : 1e-6
# D_lr : 1e-5
# f_lr : 1e-6

# min_lr * 0.05
invD_lr : 5e-7
D_lr : 5e-7
f_lr : 5e-7