# from ..base_config import BaseDataConfig
# from easydict import EasyDict as edict
# # from ...data.maze.maze_data_loader import *
# from ...data import *


# MODE_DICT = {
#     "sc" : Maze_AgentCentric_StateConditioned,
#     "sc_dreamer" : Maze_AgentCentric_StateConditioned,
#     "simpl" : Maze_AgentCentric_StateConditioned,
#     "skimo" : Maze_AgentCentric_StateConditioned,
#     "gc_skimo" : Maze_AgentCentric_StateConditioned,
#     "gc_div_joint" : Maze_AgentCentric_GoalConditioned_Diversity,
#     "wae" : Maze_AEDataset
# }


env_name : "maze"
robotics : false

state_dim : 4
n_obj : 4
n_env : 0
n_goal : 2
action_dim : 2
normalize : false

subseq_len : 11
max_seq_len : 2000
data_dir : "."
epoch_cycles_train : 20


batch_size : 1024
mixin_start : 75
mixin_ratio : 0.05
plan_H : 100
epochs : 150
warmup_steps : 75

latent_dim : 10
latent_state_dim : 32
reg_beta : 0.01
prior_state_dim : 4
wae_coef : 1
val_data_size : 5000

time_limit : 4000
target_kl_start : 5
target_kl_end : 5
init_alpha : 0.05
only_increase : false
auto_alpha : true
reuse_rate : 128
q_warmup : 5000
q_weight : 1
precollect : 20
early_stop_threshold : 0.8
max_reward : 100
use_hidden : true
consistency_lr : 1e-8
policy_lr : 3e-6