env_name : maze
manipulation : false
envtask_cfg : LVD.envs.Maze_EnvTaskConfig
binary_reward : false
std_factor : 1.35

# Skimo
# WGCSL / RIS

reward_threshold : 10


state_dim : 4
# n_obj : 4
# n_env : 0
n_pos : 2
n_nonPos : 2
n_env : 0
n_goal : 2
action_dim : 2
normalize : false
offline_buffer_size : 10000


subseq_len : 11
max_seq_len : 2000
# epoch_cycles_train : 80
epoch_cycles_train : 320

step_per_ep : 400
batch_size : 1024
mixin_start : 1
mixin_ratio : 0.1
# plan_H : 100
plan_H : 1000
# epochs : 150
epochs : 110
warmup_steps : 50

skill_dim : 10
latent_state_dim : 256
# reg_beta : 0.01
reg_beta : 5e-4
prior_state_dim : 4
wae_coef : 1
val_data_size : 5000

time_limit : 3000
target_kl_start : 5
target_kl_end : 5
# init_alpha : 0.05
init_alpha : 0.01
increasing_alpha : false
auto_alpha : true
# reuse_rate : 128
reuse_rate : 512
q_warmup : 5000
q_weight : 1
precollect : 20
early_stop_threshold : ${multiply:100, 0.8}
max_reward : 100
use_hidden : true
consistency_lr : 3e-5
policy_lr : 3e-5


buffer_size : 20000
n_episode : 50
kl_decay : 0.99


invD_lr : 1e-6
D_lr : 1e-5
f_lr : 1e-6
