env_name : maze
robotics : false
envtask_cfg : LVD.envs.Maze_EnvTaskConfig


state_dim : 4
n_obj : 4
n_env : 0
n_goal : 2
action_dim : 2
normalize : false

subseq_len : 11
max_seq_len : 2000
epoch_cycles_train : 20


batch_size : 1024
mixin_start : 75
mixin_ratio : 0.05
plan_H : 100
epochs : 150
warmup_steps : 75

skill_dim : 10
latent_state_dim : 64
reg_beta : 0.01
prior_state_dim : 4
wae_coef : 1
val_data_size : 5000

time_limit : 4000
target_kl_start : 5
target_kl_end : 5
init_alpha : 0.05
increasing_alpha : false
auto_alpha : true
reuse_rate : 128
q_warmup : 5000
q_weight : 1
precollect : 20
early_stop_threshold : ${multiply:100, 0.8}
max_reward : 100
use_hidden : true
consistency_lr : 3e-5
policy_lr : 3e-5


buffer_size : 20000
n_episode : 150
kl_decay : 0.99