hydra:
  run:
    dir: logs/${env.env_name}/${structure}/${config_path:${hydra.job.override_dirname}}
  job:
    config:
      override_dirname:
        exclude_keys:
          # common 
          - seed 
          - phase
          - rl_batch_size
          - zeroshot 
          - hindsight_relabel
          - resume
          - resume_ckpt 
          # rl 
          - rl.q_warmup
          - rl.discount
          - rl.tau
          - rl.qf_lr
          - rl.alpha_lr
          - rl.precollect
          - rl.render_period
          - rl.rl_batch_size
          - rl.norm
          # env 
          - env.policy_lr
          - env.consistency_lr
          - env.init_alpha
          - env.auto_alpha
          - env.increasing_alpha
          - env.target_kl_start
          - env.target_kl_end
          - env.kl_decay
          - env.reuse_rate
          - env.invD_lr
          - env.D_lr
          - env.f_lr
          - env.q_warmup
          # model 
          - model.consistency_update 
          - model.q_function.norm_cls
          - model.with_gcsl
          # eval
          - eval_mode
          - n_eval 


seeds :
  - 222
  - 444
  - 666

phase : skill
trainer_cls : ${get_trainer:${phase}, ${model.skill_trainer}, ${model.rl_trainer}}
eval_mode : false
n_eval : 19

resume : false 
resume_ckpt : 0
zeroshot : false
hindsight_relabel : true

save_ckpt : 50
early_stop_rounds : 100
n_rollout_steps : 10
workers : 16
dataset_size : -1
val_data_size : 5000
batch_size : 1024
lr : 1e-3
init_grad_clip : 5.0
init_grad_clip_step : 0
schedulerClass : LVD.utils.Scheduler_Helper
scheduler_params : 
  mode: 'min'        
  factor: 0.2
  patience: 6
  verbose: True
  threshold: 1e-5
  threshold_mode: abs
  # threshold: 0.005
  # threshold_mode: rel
  # min_lr: 1e-6
  min_lr: 1e-6

rl :
  render_period : 10
  q_warmup : 10_000 
  discount : 0.99
  tau : 0.005
  qf_lr : 3e-4
  alpha_lr : 3e-4
  precollect : 20
  norm : false
  rl_batch_size : 256

rl_cfgs : [
  rl_batch_size, # general
  q_warmup, discount, tau, # qfs
  policy_lr, consistency_lr, qf_lr, alpha_lr, # lrs
  consistency_update, model_update, init_alpha, auto_alpha, increasing_alpha, target_kl_start, target_kl_end, kl_decay, # sac hyper params
  tanh, # distribution   
  gc,
  with_gcsl,
  hindsight_relabel
  ]