defaults:
  - common
  - model: flat_wgcsl
  - env : kitchen

structure : flat_wgcsl
dataset_cls : LVD.data.Kitchen_Dataset_Flat_WGCSL

env:
  policy_lr : 3e-5

model:
  policy:
    in_feature : ${add:${env.state_dim}, ${env.n_goal}} 
    out_dim : ${multiply:${env.action_dim}, 2}
    # out_dim : ${env.action_dim}


  q_function:
    in_feature: ${add:${env.state_dim}, ${env.n_goal}, ${env.action_dim}} 
      # in_feature: ${add:${env.state_dim}, ${env.skill_dim}} 
