defaults:
  - common
  - model: ris
  - env : maze

structure : flat_ris
dataset_cls : LVD.data.Maze_Dataset_Flat_RIS


env:
  policy_lr : 3e-5
model:
  policy:
    in_feature : ${add:${env.state_dim}, ${env.n_goal}} 
    out_dim : ${multiply:${env.action_dim}, 2}
    n_blocks : 3
    hidden_dim : 32
    module_type : linear
    linear_cls : LVD.modules.base.LinearBlock
    norm_cls : torch.nn.LayerNorm
    act_cls : torch.nn.Mish
    tanh : true
    bias : true
    dropout : 0

  high_level_policy:
    in_feature : ${add:${env.state_dim}, ${env.n_goal}} 
    out_dim : ${multiply:${env.state_dim}, 2}
    n_blocks : 2
    hidden_dim : 32
    module_type : linear
    linear_cls : LVD.modules.base.LinearBlock
    norm_cls : torch.nn.LayerNorm
    act_cls : torch.nn.Mish
    tanh : false
    bias : true
    dropout : 0

  q_function:
    in_feature: ${add:${env.state_dim}, ${env.n_goal}, ${env.action_dim}} 
      # in_feature: ${add:${env.state_dim}, ${env.skill_dim}} 
    n_blocks : 2
    hidden_dim : 32
    out_dim : 1
    module_type : linear
    linear_cls : LVD.modules.base.LinearBlock
    norm_cls : torch.nn.LayerNorm
    act_cls : torch.nn.Mish
    bias : true
    dropout : 0