defaults:
  - common
  - model: flat_gcsl
  - env : maze

structure : flat_gcsl
dataset_cls : LVD.data.Maze_Dataset_Flat

env:
  policy_lr : 3e-5

model:
  policy:
    in_feature : ${add:${env.state_dim}, ${env.n_goal}} 
    out_dim : ${multiply:${env.action_dim}, 2}    

  q_function:
    in_feature: ${add:${env.state_dim}, ${env.n_goal}, ${env.action_dim}} 
