defaults:
  - common
  - model: flat_wgcsl
  - env : maze

eps_adv : 0.5

structure : flat_wgcsl
dataset_cls : LVD.data.Maze_Dataset_Flat_WGCSL
env:
  policy_lr : 3e-5 # for few-shot adaptation. See models.wgcsl.WGCSL.reset_optimizers() 
  
model:
  policy:
    in_feature : ${add:${env.state_dim}, ${env.n_goal}} 
    out_dim : ${multiply:${env.action_dim}, 2}

  q_function:
    in_feature: ${add:${env.state_dim}, ${env.n_goal}, ${env.action_dim}} 