defaults:
  - common
  - model: flat_gcsl
  - env : kitchen

structure : flat_gcsl
dataset_cls : LVD.data.Kitchen_Dataset_Flat

env:
  policy_lr : 3e-5 # for few-shot adpatation 

model:
  policy:
    in_feature : ${add:${env.state_dim}, ${env.n_goal}} 
    out_dim : ${multiply:${env.action_dim}, 2}

  q_function:
    in_feature: ${add:${env.state_dim}, ${env.n_goal}, ${env.action_dim}} 
