defaults:
  - common
  - model: gc_spirl
  - env : kitchen

dataset_cls : LVD.data.Kitchen_Dataset
structure : gc_spirl

scheduler_params:
  min_lr: 1e-6

env:
  auto_alpha : false
  policy_lr : 3e-5  # for few-shot adaptation 
  gcsl_lr : 3e-5    # for gcsl
  init_alpha : 1e-2 # for policy regularization


model:
  prior:
    in_feature : ${env.n_pos}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_encoder:
    in_feature: ${add:${env.state_dim}, ${env.action_dim}}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_decoder:
    in_feature : ${add:${env.n_pos}, ${env.skill_dim}} 
    out_dim : ${env.action_dim} 
    state_dim : ${env.n_pos}
    z_dim  : ${env.skill_dim}


  high_policy:
    in_feature : ${add:${env.state_dim}, ${env.n_goal}} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  q_function:
    in_feature: ${add:${env.n_pos}, ${env.n_goal}, ${env.skill_dim}} 
      # in_feature: ${add:${env.state_dim}, ${env.skill_dim}} 
