defaults:
  - common
  - model: ours_sep
  - env : kitchen

dataset_cls : LVD.data.Kitchen_Dataset_Div
structure : gc_div_joint_sep
env:
  epoch_cycles_train: ${get_cycle:${env.batch_size}}
model:
  state_encoder :
    in_feature : ${env.state_dim} 
    latent_state_dim : ${env.latent_state_dim}
    ppc_state_dim : ${env.n_obj}
    env_state_dim : ${env.n_env}
    out_dim : ${get_outdim:${env.latent_state_dim}, ${model.distributional}} 
  

  state_decoder :
    in_feature : ${env.latent_state_dim}
    latent_state_dim : ${env.latent_state_dim}
    ppc_state_dim : ${env.n_obj}
    env_state_dim : ${env.n_env}
    out_dim : ${env.state_dim}

  dynamics :
    # in_feature : ${add:${env.latent_state_dim}, ${env.skill_dim}} 
    in_feature : ${add:${divide:${env.latent_state_dim}, 2}, ${env.skill_dim}}
    out_dim : ${env.latent_state_dim} 
  
  diff_decoder:
    in_feature : ${divide:${env.latent_state_dim}, 2}
    out_dim : ${env.n_env}
    

  inverse_dynamics :
    in_feature : ${multiply:${env.latent_state_dim}, 2} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  subgoal_generator :
    in_feature : ${add:${env.latent_state_dim}, ${env.n_goal}} 
    out_dim : ${env.latent_state_dim}

  prior:
    in_feature : ${divide:${env.latent_state_dim},2}
    out_dim : ${multiply:${env.skill_dim}, 2}

  state_to_ppc:
    in_feature : ${env.latent_state_dim} 
    out_dim : ${env.latent_state_dim}

  ppc:
    in_feature : ${env.state_dim} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_encoder:
    in_feature: ${add:${env.state_dim}, ${env.action_dim}}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_decoder:
    in_feature : ${add:${env.state_dim}, ${env.skill_dim}} 
    # in_feature : ${add:${env.n_obj}, ${env.skill_dim}} 
    out_dim : ${env.action_dim} 
    state_dim : ${env.state_dim}
    z_dim  : ${env.skill_dim}

  q_function:
    in_feature: ${add:${env.latent_state_dim}, ${env.n_goal}, ${env.skill_dim}} 