defaults:
  - common
  - model: ours
  - env : kitchen

dataset_cls : "LVD.data.kitchen.kitchen_dataloader.Kitchen_Dataset_Div"
structure : gc_div_joint

model:
  state_encoder :
    in_feature : ${env.state_dim} 
    out_dim : ${env.latent_state_dim} 
  
  state_decoder :
    in_feature : ${env.latent_state_dim}
    out_dim : ${env.state_dim}

  dynamics :
    in_feature : ${add:${env.latent_state_dim}, ${env.skill_dim}} 
    out_dim : ${env.latent_state_dim} 

  inverse_dynamics :
    in_feature : ${multiply:${env.latent_state_dim}, 2} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  subgoal_generator :
    in_feature : ${add:${env.state_dim}, ${env.n_goal}} 
    out_dim : ${env.latent_state_dim}

  prior:
    in_feature : ${env.latent_state_dim} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_encoder:
    in_feature: ${add:${env.state_dim}, ${env.action_dim}}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_decoder:
    in_feature : ${add:${env.state_dim}, ${env.skill_dim}} 
    out_dim : ${env.action_dim} 
    z_dim  : ${env.skill_dim}


  q_function:
    in_feature: ${add:${env.state_dim}, ${env.n_goal}} 