defaults:
  - common
  - model: ours
  - env : kitchen

dataset_cls : LVD.data.Kitchen_Dataset_Div
structure : ours_short

env:
  skill_len : 5

scheduler_params:
  min_lr: 1e-6

model:
  state_encoder :
    in_feature : ${env.state_dim} 
    latent_state_dim : ${env.latent_state_dim}
    env_state_dim : ${env.n_env}
    ppc_state_dim : ${add:${env.n_pos}, ${env.n_nonPos}}
    pos_state_dim : ${env.n_pos}
    nonPos_state_dim : ${env.n_nonPos}
    out_dim : ${env.latent_state_dim}
  
  state_decoder :
    in_feature : ${env.latent_state_dim}
    latent_state_dim : ${env.latent_state_dim}
    env_state_dim : ${env.n_env}
    ppc_state_dim : ${add:${env.n_pos}, ${env.n_nonPos}}
    pos_state_dim : ${env.n_pos}
    nonPos_state_dim : ${env.n_nonPos}
    out_dim : ${env.state_dim}

  dynamics :
    # in_feature : ${get_D_dim:${env.latent_state_dim}, ${env.skill_dim}, ${model.diff.skill}}
    in_feature : ${add:${env.latent_state_dim}, ${env.skill_dim}}
    out_dim : ${env.latent_state_dim} 
  
  flat_dynamics :
    in_feature : ${add:${env.latent_state_dim}, ${env.skill_dim}}
    out_dim : ${env.latent_state_dim} 

  diff_decoder:
    in_feature : ${divide:${env.latent_state_dim}, 2}
    out_dim : ${env.n_env}
    
  inverse_dynamics :
    in_feature : ${multiply:${env.latent_state_dim}, 2} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  subgoal_generator :
    in_feature : ${add:${env.latent_state_dim}, ${multiply:${env.n_goal}, ${model.goal_factor}}} 
    out_dim : ${env.latent_state_dim}

  prior:
    in_feature : ${divide:${env.latent_state_dim},2}
    # in_feature : ${env.latent_state_dim}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_encoder:
    in_feature: ${add:${env.state_dim}, ${env.action_dim}}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_decoder:
    in_feature : ${add:${env.n_pos}, ${env.skill_dim}} 
    out_dim : ${env.action_dim} 
    state_dim : ${env.n_pos}
    z_dim  : ${env.skill_dim}

  high_policy:
    in_feature : ${add:${env.latent_state_dim}, ${env.n_goal}} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  goal_encoder:
    in_feature: ${env.n_goal} 
    out_dim : 16 

  goal_decoder:
    in_feature: 8
    out_dim : ${env.n_goal}

  q_function:
    in_feature: ${add:${env.latent_state_dim}, ${env.n_goal}, ${env.skill_dim}} 