defaults:
  - common
  - model: ours_sep
  - env : kitchen

dataset_cls : LVD.data.Kitchen_Dataset_Div_Sep
structure : gc_div_joint_sep

scheduler_params:
  min_lr: 1e-6

model:
  state_encoder :
    in_feature : ${env.state_dim} 
    latent_state_dim : ${env.latent_state_dim}
    env_state_dim : ${env.n_env}
    ppc_state_dim : ${add:${env.n_pos}, ${env.n_nonPos}}
    pos_state_dim : ${env.n_pos}
    nonPos_state_dim : ${env.n_nonPos}
    out_dim : ${env.latent_state_dim}
    # out_dim : ${get_outdim:${env.latent_state_dim}, ${model.distributional}} 
  

  state_decoder :
    in_feature : ${env.latent_state_dim}
    latent_state_dim : ${env.latent_state_dim}
    env_state_dim : ${env.n_env}
    ppc_state_dim : ${add:${env.n_pos}, ${env.n_nonPos}}
    pos_state_dim : ${env.n_pos}
    nonPos_state_dim : ${env.n_nonPos}
    out_dim : ${env.state_dim}


  dynamics :
    # in_feature : ${add:${env.latent_state_dim}, ${env.skill_dim}} 
    in_feature : ${add:${divide:${env.latent_state_dim}, 2}, ${env.skill_dim}}
    out_dim : ${env.latent_state_dim} 
  
  diff_decoder:
    in_feature : ${divide:${env.latent_state_dim}, 2}
    out_dim : ${env.n_env}
    
  inverse_dynamics :
    in_feature : ${multiply:${env.latent_state_dim}, 2} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  subgoal_generator :
    # in_feature : ${add:${env.latent_state_dim}, ${env.n_goal}} 
    in_feature : ${add:${env.latent_state_dim}, ${multiply:${env.n_goal}, ${model.goal_factor}}} 

    out_dim : ${env.latent_state_dim}
    # latent_state_dim : ${env.latent_state_dim}
    # n_goal : ${env.n_goal}
    # block_cls : LVD.modules.TransformerBlock
    # module_type : transformer


  prior:
    in_feature : ${divide:${env.latent_state_dim},2}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_encoder:
    in_feature: ${add:${env.state_dim}, ${env.action_dim}}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_decoder:
    # in_feature : ${get_indim:${env.manipulation}, ${env.state_dim}, ${env.n_pos}, ${env.skill_dim}} 
    in_feature : ${add:${env.n_pos}, ${env.skill_dim}} 
    out_dim : ${env.action_dim} 
    state_dim : ${env.n_pos}
    z_dim  : ${env.skill_dim}

  q_function:
    in_feature: ${add:${env.latent_state_dim}, ${env.n_goal}, ${env.skill_dim}} 