defaults:
  - common
  - model: ours_sep
  - env : maze

dataset_cls : LVD.data.Maze_Dataset_Div_Sep
structure : gc_div_joint_sep

scheduler_params:
  min_lr: 1e-5


model:
  state_encoder :
    in_feature : ${env.state_dim} 
    latent_state_dim : ${env.latent_state_dim}
    ppc_state_dim : ${env.n_obj}
    env_state_dim : ${env.n_env}
    out_dim : ${env.latent_state_dim}
  
  state_decoder :
    in_feature : ${env.latent_state_dim}
    latent_state_dim : ${env.latent_state_dim}
    ppc_state_dim : ${env.n_obj}
    env_state_dim : ${env.n_env}
    out_dim : ${env.state_dim}

  dynamics :
    in_feature : ${add:${env.latent_state_dim}, ${env.skill_dim}}
    out_dim : ${env.latent_state_dim} 
  
  diff_decoder:
    in_feature : ${divide:${env.latent_state_dim}, 2}
    out_dim : ${env.n_env}
    
  inverse_dynamics :
    in_feature : ${multiply:${env.latent_state_dim}, 2} 
    out_dim : ${multiply:${env.skill_dim}, 2}

  subgoal_generator :
    in_feature : ${add:${env.latent_state_dim}, ${env.n_goal}} 
    out_dim : ${env.latent_state_dim}

  prior:
    in_feature : ${env.latent_state_dim}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_encoder:
    in_feature: ${add:${env.state_dim}, ${env.action_dim}}
    out_dim : ${multiply:${env.skill_dim}, 2}

  skill_decoder:
    in_feature : ${add:${env.state_dim}, ${env.skill_dim}}
    out_dim : ${env.action_dim} 
    state_dim : ${get_statedim:${model.decode_only_ppc}, ${env.state_dim}, ${env.n_obj}}
    z_dim  : ${env.skill_dim}

  q_function:
    in_feature: ${add:${env.latent_state_dim}, ${env.n_goal}, ${env.skill_dim}} 